default_install_hook_types:
  - pre-commit
  - commit-msg
  - post-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=md ]
    - id: check-toml
    - id: detect-private-key

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.26
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-format
        always_run: true
      - id: ruff-check
        args: [ --output-format, concise, --exit-zero ]
        verbose: true

  - repo: ../commit_hooks
    rev: ee4943fca50ec1f48f1e8ad76317336e7bf30b55
    hooks:
      - id: check-commit-msg
      - id: changelog-helper
      - id: recreate-changelog
      - id: bump-version-helper
      - id: bump-version
      - id: bump-version-finalize
