default_install_hook_types:
  - pre-commit
  - commit-msg
  - post-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=md ]
    - id: check-toml
    - id: detect-private-key

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.18
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      - id: ruff-format
        always_run: true
      - id: ruff-check
        args: [ --output-format, concise, --exit-zero ]
        verbose: true

  - repo: https://github.com/kapsner/commit_hooks
    rev: 0f39c0ba127341fdb8147c53d90b904fdddff0f4
    hooks:
      - id: check-commit-msg
      - id: changelog-helper
      - id: recreate-changelog
      - id: bump-version
